//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketAutomationAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentManagement_WeeklyData
    {
        public decimal PayrollDataId { get; set; }
        public string IncidentId { get; set; }
        public string NotificationText { get; set; }
        public Nullable<int> SeverityNumber { get; set; }
        public string Status { get; set; }
        public string SuspendReason { get; set; }
        public string Assignee { get; set; }
        public string AssigneeGroup { get; set; }
        public string StatusTracking { get; set; }
        public string ETR { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string UpdatedIP { get; set; }
        public byte[] HashBytes { get; set; }
        public Nullable<bool> Finalized { get; set; }
        public Nullable<bool> TBD { get; set; }
    }
}
