//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketAutomationAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketAutomationEntities : DbContext
    {
        public TicketAutomationEntities()
            : base("name=TicketAutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IncidentManagement_Data> IncidentManagement_Data { get; set; }
        public virtual DbSet<IncidentManagement_WeeklyData> IncidentManagement_WeeklyData { get; set; }
    }
}
